export const industryList = [
  {
    id: 'mining',
    name: 'Mining',
    subCategories: [
      'Open Cast',
      'Underground',
      'Marine Mining',
      'Services',
      'Equipment',
      'Research',
      'Exploration',
      'Supplies',
      'Mineral Processing',
      'Engineering',
    ],
  },
  {
    id: 'construction',
    name: 'Construction',
    subCategories: [
      'Residential',
      'Commercial',
      'Infrastructure',
      'Engineering',
      'Material',
    ],
  },
  {
    id: 'information-technology-and-communication',
    name: 'Information Technology and Communication',
    subCategories: ['Software Development', 'Telecommunications', 'IT Support'],
  },
  {
    id: 'health',
    name: 'Health',
    subCategories: [
      'Pharmaceuticals',
      'Healthcare Services',
      'Medical Devices',
    ],
  },
  {
    id: 'government',
    name: 'Government',
    subCategories: [
      'Public Administration',
      'Local Government',
      'National Government',
    ],
  },
  {
    id: 'education',
    name: 'Education',
    subCategories: [
      'Higher Education',
      'Vocational Training',
      'E-Learning',
      'Research Education',
    ],
  },
  {
    id: 'agriculture',
    name: 'Agriculture',
    subCategories: ['Crop Production', 'Livestock', 'Agri-Tech'],
  },
  {
    id: 'manufacturing',
    name: 'Manufacturing',
    subCategories: ['Food & Beverage', 'Textiles', 'Automotive'],
  },
  {
    id: 'retail-and-wholesale',
    name: 'Retail and Wholesale',
    subCategories: ['E-commerce', 'Brick and Mortar', 'Wholesale'],
  },
  {
    id: 'hospitality',
    name: 'Hospitality',
    subCategories: ['Hotels', 'Restaurants', 'Travel Services'],
  },
  {
    id: 'transport-and-logistics',
    name: 'Transport and Logistics',
    subCategories: ['Freight', 'Warehousing', 'Shipping'],
  },
  {
    id: 'financial-services',
    name: 'Financial Services',
    subCategories: ['Banking', 'Insurance', 'Investment'],
  },
  {
    id: 'telecommunications',
    name: 'Telecommunications',
    subCategories: [
      'Mobile Services',
      'Internet Services',
      'Satellite Services',
      'Research',
      'Radio Services',
      'Television Services',
    ],
  },
  {
    id: 'energy-and-utilities',
    name: 'Energy and Utilities',
    subCategories: [
      'Renewable Energy',
      'Water Supply',
      'Waste Management',
      'Oil & Gas',
      'Electricity Supply',
      'Gas Supply',
      'Nuclear Energy',
      'Energy Services',
      'Research',
    ],
  },
  {
    id: 'real-estate',
    name: 'Real Estate',
    subCategories: [
      'Residential',
      'Commercial',
      'Property Management',
      'Construction',
      'Development',
    ],
  },
  {
    id: 'media-and-entertainment',
    name: 'Media and Entertainment',
    subCategories: [
      'Television',
      'Film Production',
      'Music',
      'Publishing',
      'Gaming',
      'Events',
    ],
  },
  {
    id: 'business-services',
    name: 'Business Services',
    subCategories: [
      'Consulting',
      'Marketing',
      'Legal Services',
      'Accounting',
      'Human Resources',
      'Recruitment',
      'Training',
      'Translation Services',
      'Event Planning',
      'Facilities Management',
      'Office Supplies',
      'Printing Services',
      'Courier Services',
      'Storage Services',
      'Business Process Outsourcing',
      'Virtual Assistance',
      'Business Intelligence',
      'Data Analytics',
      'Market Research',
      'Risk Management',
      'Quality Assurance',
      'Compliance Services',
      'Business Development',
      'Sales',
      'Customer Service',
      'Public Relations',
      'Advertising',
      'Branding',
    ],
  },
  {
    id: 'public-services',
    name: 'Public Services',
    subCategories: [
      'Social Services',
      'Community Development',
      'Public Healthcare',
      'Political Entities',
      'Water Works & Supply',
      'Electricity Supply',
      'Sanitation Services',
      'Fire Services',
      'Emergency Services',
      'Transport',
      'Education',
      'Libraries',
      'Recreation',
      'Parks',
      'Sports Facilities',
      'Arts & Culture',
      'Events',
      'Safety',
      'Roads',
      'Infrastructure',
      'Housing',
      'Health',
      'Municipal Services',
      'Works',
      'Administration',
      'Policy',
      'Finance',
      'Post Office',
      "Mayor's Office",
      'City Council',
      'City Manager',
      'Religious Services',
      'Cemeteries',
      'Funeral Services',
    ],
  },
  {
    id: 'general-services',
    name: 'General Services',
    subCategories: [
      'Cleaning Services',
      'Maintenance Services',
      'Security Services',
    ],
  },
  {
    id: 'security',
    name: 'Security',
    subCategories: [
      'Guards Armed',
      'Guards Unarmed',
      'Covert Operations',
      'Cash Transport',
      'Personal Protection',
      'Police',
      'Military Defense Force',
    ],
  },
];
