export const dataPackages = {
  uncapped_vodacom_fixed_lte: [
    {
      data_size_gb: 50,
      stock_price: 269,
      selling_price: 289,
      terms: 'Speed Dependent on Router & LTE Tower',
      max_bandwidth_mbps: 20,
      aup_limit_speed_mbps: 2,
    },
    {
      data_size_gb: 150,
      stock_price: 369,
      selling_price: 389,
      terms: 'Speed Dependent on Router & LTE Tower',
      max_bandwidth_mbps: 30,
      aup_limit_speed_mbps: 2,
    },
    {
      data_size_gb: 300,
      stock_price: 469,
      selling_price: 489,
      terms: 'Speed Dependent on Router & LTE Tower',
      max_bandwidth_mbps: 50,
      aup_limit_speed_mbps: 2,
    },
    {
      data_size_gb: 600,
      stock_price: 669,
      selling_price: 689,
      terms: 'Speed Dependent on Router & LTE Tower',
      max_bandwidth_mbps: 'Uncapped',
      aup_limit_speed_mbps: 1,
    },
  ],
  capped_vodacom_fixed_lte: [
    {
      data_size_gb: 25,
      stock_price: 169,
      selling_price: 189,
      terms: '1 Month Data Rollover applies to Capped Vodacom Fixed LTE',
      max_bandwidth_mbps: 'Unknown',
      aup_limit_speed_mbps: 'Unknown',
    },
    {
      data_size_gb: 50,
      stock_price: 269,
      selling_price: 289,
      terms: '1 Month Data Rollover applies to Capped Vodacom Fixed LTE',
      max_bandwidth_mbps: 'Unknown',
      aup_limit_speed_mbps: 'Unknown',
    },
    {
      data_size_gb: 100,
      stock_price: 369,
      selling_price: 389,
      terms: '1 Month Data Rollover applies to Capped Vodacom Fixed LTE',
      max_bandwidth_mbps: 'Unknown',
      aup_limit_speed_mbps: 'Unknown',
    },
    {
      data_size_gb: 200,
      stock_price: 469,
      selling_price: 489,
      terms: '1 Month Data Rollover applies to Capped Vodacom Fixed LTE',
      max_bandwidth_mbps: 'Unknown',
      aup_limit_speed_mbps: 'Unknown',
    },
  ],
  uncapped_vodacom_fixed_5g: [
    {
      data_size_gb: 250,
      stock_price: 445,
      selling_price: 475,
      terms: '',
      max_bandwidth_mbps: 500,
      aup_limit_speed_mbps: 2,
    },
    {
      data_size_gb: 350,
      stock_price: 645,
      selling_price: 675,
      terms: '',
      max_bandwidth_mbps: 500,
      aup_limit_speed_mbps: 2,
    },
    {
      data_size_gb: 550,
      stock_price: 845,
      selling_price: 875,
      terms: '',
      max_bandwidth_mbps: 500,
      aup_limit_speed_mbps: 2,
    },
    {
      data_size_gb: 750,
      stock_price: 945,
      selling_price: 975,
      terms: '',
      max_bandwidth_mbps: 500,
      aup_limit_speed_mbps: 2,
    },
  ],
  capped_telkom_fixed_lte: [
    {
      data_size_night_gb: 22.5,
      data_size_day_gb: 22.5,
      stock_price: 179,
      selling_price: 199,
      terms: 'Unknown',
      max_bandwidth_mbps: 'Unknown',
      aup_limit_speed_mbps: 'Unknown',
    },
    {
      data_size_night_gb: 40,
      data_size_day_gb: 40,
      stock_price: 225,
      selling_price: 245,
      terms: 'Unknown',
      max_bandwidth_mbps: 'Unknown',
      aup_limit_speed_mbps: 'Unknown',
    },
    {
      data_size_night_gb: 80,
      data_size_day_gb: 80,
      stock_price: 255,
      selling_price: 275,
      terms: 'Unknown',
      max_bandwidth_mbps: 'Unknown',
      aup_limit_speed_mbps: 'Unknown',
    },
    {
      data_size_night_gb: 120,
      data_size_day_gb: 120,
      stock_price: 310,
      selling_price: 330,
      terms: 'Unknown',
      max_bandwidth_mbps: 'Unknown',
      aup_limit_speed_mbps: 'Unknown',
    },
    {
      data_size_night_gb: 180,
      data_size_day_gb: 180,
      stock_price: 410,
      selling_price: 430,
      terms: 'Unknown',
      max_bandwidth_mbps: 'Unknown',
      aup_limit_speed_mbps: 'Unknown',
    },
    {
      data_size_night_gb: 2000,
      data_size_day_gb: 2000,
      stock_price: 775,
      selling_price: 795,
      terms: 'Unknown',
      max_bandwidth_mbps: 'Unknown',
      aup_limit_speed_mbps: 'Unknown',
    },
  ],
  uncapped_mtn_fixed_5g: [
    {
      data_size_gb: 300,
      stock_price: 399,
      selling_price: 424,
      terms: 'Speed dependant on 5G router & 5G Tower',
      max_bandwidth_mbps: 500,
      aup_limit_speed_mbps: 2,
    },
    {
      data_size_gb: 450,
      stock_price: 549,
      selling_price: 574,
      terms: 'Speed dependant on 5G router & 5G Tower',
      max_bandwidth_mbps: 500,
      aup_limit_speed_mbps: 2,
    },
    {
      data_size_gb: 600,
      stock_price: 649,
      selling_price: 674,
      terms: 'Speed dependant on 5G router & 5G Tower',
      max_bandwidth_mbps: 500,
      aup_limit_speed_mbps: 2,
    },
    {
      data_size_gb: 1000,
      stock_price: 849,
      selling_price: 874,
      terms: 'Speed dependant on 5G router & 5G Tower',
      max_bandwidth_mbps: 500,
      aup_limit_speed_mbps: 2,
    },
  ],
  mtn_3g_lte: [
    {
      data_size_gb: 2.5,
      stock_price: 64,
      selling_price: 84,
      terms: 'Once off sim activation fee R49 Top Up R38/gb',
      max_bandwidth_mbps: 'Unknown',
      aup_limit_speed_mbps: 'Unknown',
    },
    {
      data_size_gb: 5.5,
      stock_price: 96,
      selling_price: 116,
      terms: 'Once off sim activation fee R49 Top Up R38/gb',
      max_bandwidth_mbps: 'Unknown',
      aup_limit_speed_mbps: 'Unknown',
    },
    {
      data_size_gb: 7.5,
      stock_price: 144,
      selling_price: 164,
      terms: 'Once off sim activation fee R49 Top Up R38/gb',
      max_bandwidth_mbps: 'Unknown',
      aup_limit_speed_mbps: 'Unknown',
    },
    {
      data_size_gb: 15,
      stock_price: 244,
      selling_price: 264,
      terms: 'Once off sim activation fee R49 Top Up R38/gb',
      max_bandwidth_mbps: 'Unknown',
      aup_limit_speed_mbps: 'Unknown',
    },
    {
      data_size_gb: 25,
      stock_price: 289,
      selling_price: 309,
      terms: 'Once off sim activation fee R49 Top Up R38/gb',
      max_bandwidth_mbps: 'Unknown',
      aup_limit_speed_mbps: 'Unknown',
    },
    {
      data_size_gb: 50,
      stock_price: 489,
      selling_price: 509,
      terms: 'Once off sim activation fee R49 Top Up R38/gb',
      max_bandwidth_mbps: 'Unknown',
      aup_limit_speed_mbps: 'Unknown',
    },
  ],
  capped_mtn_fixed_lte: [
    {
      data_size_night_gb: 40,
      data_size_gb: 40,
      stock_price: 64,
      selling_price: 84,
      terms: 'Night data used between 00:00 - 6am',
      max_bandwidth_mbps: 'Unknown',
      aup_limit_speed_mbps: 'Unknown',
    },
    {
      data_size_night_gb: 90,
      data_size_gb: 90,
      stock_price: 249,
      selling_price: 269,
      terms: 'Night data used between 00:00 - 6am',
      max_bandwidth_mbps: 'Unknown',
      aup_limit_speed_mbps: 'Unknown',
    },
    {
      data_size_night_gb: 200,
      data_size_gb: 'Unlimited',
      stock_price: 539,
      selling_price: 559,
      terms: 'Night data used between 00:00 - 6am (Uncapped night promotional)',
      max_bandwidth_mbps: 'Unknown',
      aup_limit_speed_mbps: 'Unknown',
    },
    {
      data_size_night_gb: 400,
      data_size_gb: 'Unlimited',
      stock_price: 729,
      selling_price: 749,
      terms: 'Night data used between 00:00 - 6am (Uncapped night promotional)',
      max_bandwidth_mbps: 'Unknown',
      aup_limit_speed_mbps: 'Unknown',
    },
  ],
};

export const networkPackages = [
  {
    id: 'uncapped_vodacom_fixed_lte',
    title: 'Vodacom Fixed LTE - Uncapped',
    description:
      'Vodacom Fixed LTE Uncapped offers unlimited data, providing consistent high-speed internet without data restrictions. This package is ideal for households and businesses requiring extensive online usage without worrying about data limits.',
    sellingPoints: [
      'Unlimited data for uninterrupted browsing and streaming.',
      'No throttling or reduced speeds, even during peak times.',
      'Ideal for multiple users and high-demand applications.',
    ],
  },
  {
    id: 'capped_vodacom_fixed_lte',
    title: 'Vodacom Fixed LTE - Capped',
    description:
      'Vodacom Fixed LTE Capped provides a fixed amount of data per month, ensuring reliable internet access with various data plan sizes to suit different usage needs. Ideal for users with predictable data consumption patterns.',
    sellingPoints: [
      'Affordable plans with clear data limits.',
      'Great for users who monitor and manage their data usage.',
      'Reliable performance for everyday tasks like browsing and email.',
    ],
  },
  {
    id: 'uncapped_vodacom_fixed_5g',
    title: 'Vodacom Fixed 5G - Uncapped',
    description:
      'Vodacom Fixed 5G Uncapped delivers high-speed 5G connectivity with unlimited data for seamless browsing, streaming, and gaming. This package is perfect for data-intensive users who require the fastest available internet.',
    sellingPoints: [
      'Experience the speed of 5G with unlimited data.',
      'Perfect for gaming, streaming, and video conferencing.',
      'Future-proof your internet with the latest technology.',
    ],
  },
  {
    id: 'capped_telkom_fixed_lte',
    title: 'Telkom Fixed LTE - Capped',
    description:
      "Telkom Fixed LTE Capped provides reliable LTE connectivity with a defined data cap. It's suitable for users who require consistent internet access for basic browsing and streaming without the need for unlimited data.",
    sellingPoints: [
      'Flexible data options to fit various budgets.',
      'Ideal for casual users and small households.',
      'Reliable internet access with fixed monthly costs.',
    ],
  },
  {
    id: 'uncapped_mtn_fixed_5g',
    title: 'MTN Fixed 5G - Uncapped',
    description:
      'MTN Fixed 5G Uncapped provides high-speed, next-gen 5G internet with unlimited data. Designed for homes and businesses, it offers powerful connectivity for heavy online activities such as gaming, streaming, and remote work.',
    sellingPoints: [
      'Unlimited high-speed data for all your online activities.',
      'Experience ultra-fast speeds with low latency.',
      'Perfect for smart homes and remote working setups.',
    ],
  },
  {
    id: 'mtn_3g_lte',
    title: 'MTN 3G/LTE - Capped',
    description:
      'MTN 3G/LTE Capped offers flexible and reliable mobile data plans for light to moderate usage. Ideal for users who need dependable internet on the go or in areas where fixed-line connections are unavailable.',
    sellingPoints: [
      'Affordable mobile data options for everyday use.',
      'Access the internet wherever you are with reliable coverage.',
      'Great for social media, browsing, and light streaming.',
    ],
  },
  {
    id: 'capped_mtn_fixed_lte',
    title: 'MTN Fixed LTE - Capped',
    description:
      'MTN Fixed LTE Capped provides a balance of speed and data control, offering a set amount of data each month. This package is perfect for homes and small offices that need steady internet access with predictable data consumption.',
    sellingPoints: [
      'Controlled data usage with fixed monthly pricing.',
      'Perfect for light users and small families.',
      'Reliable performance for browsing and streaming.',
    ],
  },
];
