export const pricing = [
  {
    item: 'Android/iOS App Development',
    startingPrice: 'R30,000',
    duration: '4-6 weeks',
    features: [
      'User-friendly mobile interface',
      'User management system',
      'Secure database integration',
      'Push notifications setup',
      'Basic authentication & authorization',
      'Compatible for both Android and iOS',
    ],
  },
  {
    item: 'Web Application Development',
    startingPrice: 'R30,000',
    duration: '6-8 weeks',
    features: [
      'Responsive design for all devices',
      'User management system',
      'Secure database integration',
      'Authentication and user roles',
      'Basic dashboard with reporting tools',
      'SEO optimization & analytics setup',
    ],
  },
  {
    item: 'Desktop Application Development',
    startingPrice: 'R35,000',
    duration: '8-10 weeks',
    features: [
      'Desktop-specific user interface',
      'User management system',
      'Local/Cloud database integration',
      'Installation & setup process',
      'Basic reporting and analytics',
      'Offline functionality with data sync',
    ],
  },
  {
    item: 'Quotation and Invoicing System',
    startingPrice: 'R36,000',
    duration: '3-4 weeks',
    features: [
      'Customizable templates for quotes and invoices',
      'User management system',
      'Secure database integration',
      'Email notifications for invoicing',
      'Reporting tools for sales tracking',
    ],
  },
  {
    item: 'Bookings and Appointments System',
    startingPrice: 'R36,000',
    duration: '4-6 weeks',
    features: [
      'User-friendly booking interface',
      'Calendar integration',
      'User management system',
      'Secure database integration',
      'Email and SMS reminders',
    ],
  },
  {
    item: 'App with Social Features',
    startingPrice: 'R30,000',
    duration: '6-8 weeks',
    features: [
      'User profiles and social connections',
      'Secure database integration',
      'User management system',
      'Real-time notifications',
      'Content sharing and messaging features',
    ],
  },
  {
    item: 'E-commerce Store App',
    startingPrice: 'R40,000',
    duration: '8-10 weeks',
    features: [
      'User-friendly shopping interface',
      'Product catalog management',
      'Secure payment gateway integration',
      'User management system',
      'Order tracking and notifications',
    ],
  },
  {
    item: 'Inventory Management System',
    startingPrice: 'R36,000',
    duration: '4-6 weeks',
    features: [
      'Real-time inventory tracking',
      'User management system',
      'Reporting tools for stock levels',
      'Secure database integration',
      'Supplier management features',
    ],
  },
  {
    item: 'Project Management App',
    startingPrice: '36,000',
    duration: '6-8 weeks',
    features: [
      'Task and project tracking',
      'User management system',
      'Collaboration tools',
      'Secure database integration',
      'Reporting tools for progress tracking',
    ],
  },
  {
    item: 'Case Management System',
    startingPrice: 'R38,000',
    duration: '8-10 weeks',
    features: [
      'Customizable case tracking',
      'User management system',
      'Secure database integration',
      'Reporting tools for case outcomes',
      'Email notifications for updates',
    ],
  },
  {
    item: 'Email, SMS, and Push Notifications for Existing System',
    startingPrice: 'R18,000',
    duration: '2-3 weeks',
    features: [
      'Integration of email notifications',
      'SMS notifications setup',
      'Push notifications for mobile apps',
      'User management system',
      'Reporting on notification engagement',
    ],
  },
  {
    item: 'Custom Static Website',
    startingPrice: 'R10,000',
    duration: '3-4 weeks',
    features: [
      'Responsive design',
      'User-friendly navigation',
      'Content management system',
      'SEO optimization',
      'Basic analytics setup',
    ],
  },
  {
    item: 'Custom Landing Page',
    startingPrice: 'R8,000',
    duration: '1-2 weeks',
    features: [
      'Responsive design',
      'Call-to-action buttons',
      'User-friendly layout',
      'SEO optimization',
      'Basic analytics setup',
    ],
  },
  {
    item: '6 Months Digital Marketing Campaign',
    startingPrice: 'R50,000',
    duration: '6 months',
    features: [
      'Targeted online advertising',
      'Social media marketing',
      'Content creation and management',
      'SEO strategies',
      'Monthly reporting and analysis',
    ],
  },
  {
    item: 'Social Media Management',
    startingPrice: 'R30,000',
    duration: '3 months',
    features: [
      'Content creation and scheduling',
      'Engagement with followers',
      'Monthly performance reports',
      'Strategy development',
      'Ad management',
    ],
  },
  {
    item: 'Leads Generation & Management System',
    startingPrice: 'R35,000',
    duration: '4-6 weeks',
    features: [
      'Lead capture forms',
      'User management system',
      'Secure database integration',
      'Reporting tools for lead tracking',
      'Integration with email marketing',
    ],
  },
];

export const team = [
  {
    id: 1,
    name: 'Zweli Mthethwa',
    title: 'Co-founder/ Software Engineer',
    imageUrl: '/team/zweli-removebg.png',
    description:
      'Zweli designs high-performance solutions and mentors the team, driving the technical vision of our projects.',
    color: '#219ebc',
  },
  {
    id: 2,
    name: 'Ayabonga Qwabi',
    title: 'Co-founder/ Software Engineer',
    imageUrl: '/team/aya-removebg.png',
    description:
      'Aya develops efficient and scalable software solutions, contributing to the innovation and functionality of our products.',
    color: '#219ebc',
  },
  {
    id: 3,
    name: 'Siyamthanda Nomgqokwana',
    title: 'IT Infrastructure / Cloud Architect',
    imageUrl: 'team/siya-removebg.png',
    description:
      'Siya architects and implements robust cloud solutions, shaping the technological foundations of our projects.',
    color: '#219ebc',
  },
  {
    id: 4,
    name: 'Matthew Fourie',
    title: 'Software Engineer',
    imageUrl: 'team/matt-removebg.png',
    description:
      'Matthew supports the development team by writing clean and maintainable code, assisting in the creation of innovative software solutions that drive project success.',
    color: '#219ebc',
  },
  {
    id: 5,
    name: 'Dyelpo KaatNanret Senshak',
    title: 'Social Media Specialist',
    imageUrl: 'team/kaatnanret-removebg.png',
    description:
      'KaatNanret manages social media pages and creates content to reach target audiences and drive conversions.',
    color: 'black',
  },
];
